"use client";

// Renders one Caissa agent turn.
//
// The point of this component is that an answer is never just prose. Every turn
// arrives with the evidence it used, the claims that were machine-checked, what
// could not be retrieved, and buttons that do something real. The layout makes
// those auditable instead of hiding them behind a "trust me" paragraph:
//
//   answer text  →  claims (typed, checked)  →  actions  →  evidence + gaps
//
// Nothing here computes a chess fact. It renders what the backend measured, and
// when the backend says something is unavailable, the UI says so too.

import Link from "next/link";

import { Disclosure, SourceBadge } from "@/components/ui";
import type { AgentAction, AgentTurnResponse } from "@/lib/api";

const CLAIM_TONE: Record<string, string> = {
  fact: "border-sky-primary/40 bg-sky-primary/10 text-sky-300",
  observation: "border-emerald-primary/40 bg-emerald-primary/10 text-emerald-300",
  interpretation: "border-violet-primary/40 bg-violet-primary/10 text-violet-300",
  coaching: "border-amber-primary/40 bg-amber-primary/10 text-amber-300",
};

/**
 * The question an action without its own route asks the agent.
 *
 * Phrased as the *question* rather than the operation ("why was X bad compared with
 * Y?") so it reaches the stored move analysis, which already holds the comparison —
 * the centipawn loss and the engine's choice. Asking instead to "compare X with Y"
 * would need a FEN the turn may not have, and a button that leads to a recorded gap
 * is barely better than no button.
 */
function promptForAction(action: AgentAction): string {
  const params = action.params ?? {};
  if (action.action === "compare_moves" && params.played && params.best) {
    return `Why was ${String(params.played)} bad compared with ${String(params.best)}?`;
  }
  return action.label;
}

function ActionButton({
  action,
  onFollowUp,
}: {
  action: AgentAction;
  onFollowUp: (prompt: string) => void;
}) {
  // A capability that is not built for this context. Shown, disabled, with the
  // reason — the gap is visible rather than silently missing.
  if (!action.available) {
    return (
      <span
        title={action.unavailable_reason ?? "Not available yet"}
        className="badge cursor-not-allowed border-ink-600 bg-ink-800 text-mist-500"
      >
        {action.label}
        {action.unavailable_reason ? " · not yet" : ""}
      </span>
    );
  }
  // A navigation: the button opens the real route and lands on the real ply.
  if (action.href) {
    return (
      <Link href={action.href} className="btn btn-ghost">
        {action.label}
      </Link>
    );
  }
  // An agent-executable request: clicking asks the coach to perform it, and the
  // comparison is returned with real engine evidence rather than faked here.
  return (
    <button type="button" className="btn btn-ghost" onClick={() => onFollowUp(promptForAction(action))}>
      {action.label}
    </button>
  );
}

export function AgentAnswerCard({
  answer,
  onFollowUp,
}: {
  answer: AgentTurnResponse;
  onFollowUp: (prompt: string) => void;
}) {
  const trace = answer.trace ?? {};
  const evidence = answer.evidence;
  const missing = evidence?.missing ?? [];
  const limitations = answer.limitations ?? [];
  const failedTools = (trace.tool_calls ?? []).filter((call) => !call.ok);

  return (
    <div className="space-y-3">
      <p className="whitespace-pre-wrap text-body leading-relaxed text-mist-100">{answer.message}</p>

      {/* How the answer was produced: deterministic or generated, how long, what it cost. */}
      <div className="flex flex-wrap items-center gap-1.5">
        <span
          className={`badge ${
            answer.deterministic
              ? "border-emerald-primary/40 bg-emerald-primary/10 text-emerald-300"
              : "border-violet-primary/40 bg-violet-primary/10 text-violet-300"
          }`}
          title={
            answer.deterministic
              ? "Answered from stored Caissa data with no language-model call."
              : `Generated by ${answer.provider ?? "an LLM"}${answer.model ? ` (${answer.model})` : ""}.`
          }
        >
          {answer.deterministic ? "no LLM call" : `${answer.provider ?? "llm"}${answer.model ? `/${answer.model}` : ""}`}
        </span>
        <span className="badge border-ink-600 bg-ink-800 mono text-mist-400">
          {trace.tool_count ?? 0} tool call{(trace.tool_count ?? 0) === 1 ? "" : "s"}
        </span>
        {typeof trace.total_ms === "number" ? (
          <span className="badge border-ink-600 bg-ink-800 mono text-mist-400">
            {Math.round(trace.total_ms)} ms
          </span>
        ) : null}
        {trace.mode ? (
          <span className="badge border-ink-600 bg-ink-800 text-mist-400">{trace.mode} mode</span>
        ) : null}
        {answer.prompt_version && !answer.deterministic ? (
          <span className="badge border-ink-600 bg-ink-800 mono text-mist-500">
            prompt {answer.prompt_version}
          </span>
        ) : null}
      </div>

      {/* Validation: the machine-checked claims. A failure is surfaced loudly. */}
      {answer.validation.checked > 0 || !answer.validation.passed ? (
        <div
          className={`rounded-lg border px-3 py-2 ${
            answer.validation.passed
              ? "border-ink-700 bg-ink-850/60"
              : "border-rose-primary/40 bg-rose-primary/10"
          }`}
        >
          <p
            className={`text-small ${
              answer.validation.passed ? "text-mist-400" : "font-medium text-rose-300"
            }`}
          >
            {answer.validation.passed ? "✓ " : "⚠ "}
            {answer.validation.summary}
          </p>
          {answer.validation.failures.length > 0 ? (
            <ul className="mt-1.5 space-y-1">
              {answer.validation.failures.map((failure, index) => (
                <li key={index} className="text-small text-rose-200">
                  <span className="mono">{failure.kind}</span>: {failure.claim}
                  {failure.detail ? ` — ${failure.detail}` : ""}
                </li>
              ))}
            </ul>
          ) : null}
        </div>
      ) : null}

      {/* Typed claims, so a reader can tell an engine fact from an interpretation. */}
      {answer.claims.length > 0 ? (
        <div className="flex flex-wrap gap-1.5">
          {answer.claims.map((claim, index) => (
            <span
              key={index}
              className={`badge ${CLAIM_TONE[claim.kind] ?? "border-ink-600 bg-ink-800 text-mist-400"}`}
              title={claim.note ?? undefined}
            >
              {claim.label}
              {claim.verified === false ? " ⚠" : ""}
            </span>
          ))}
        </div>
      ) : null}

      {/* Real actions, backed by data this turn retrieved. */}
      {answer.actions.length > 0 ? (
        <div className="flex flex-wrap gap-2 border-t border-ink-800 pt-3">
          {answer.actions.map((action, index) => (
            <ActionButton key={index} action={action} onFollowUp={onFollowUp} />
          ))}
        </div>
      ) : null}

      {/* The audit trail: evidence, gaps, limitations and the tool trace. */}
      {evidence || missing.length > 0 || failedTools.length > 0 ? (
        <Disclosure summary={`Evidence and reasoning (${evidence?.items.length ?? 0} item(s))`}>
          {evidence && evidence.items.length > 0 ? (
            <ul className="space-y-1.5">
              {evidence.items.map((item, index) => (
                <li key={index} className="rounded-lg border border-ink-700 bg-ink-850/60 px-2.5 py-2">
                  <div className="flex flex-wrap items-center gap-1.5">
                    <SourceBadge source={item.source} label={item.kind.toLowerCase().replace(/_/g, " ")} />
                    <span className="badge mono border-ink-600 bg-ink-800 text-mist-400">{item.tool}</span>
                    {item.certainty === "candidate" ? (
                      <span className="badge border-amber-primary/40 bg-amber-primary/10 text-amber-300">
                        candidate
                      </span>
                    ) : null}
                    <span className="mono text-small text-mist-500">{item.ref}</span>
                  </div>
                  <p className="mt-1 text-small leading-relaxed text-mist-300">{item.summary}</p>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-small text-mist-500">No stored evidence matched this question.</p>
          )}

          {missing.length > 0 ? (
            <div className="rounded-lg border border-amber-primary/30 bg-amber-primary/8 px-2.5 py-2">
              <p className="text-small font-medium text-amber-300">Could not be retrieved</p>
              <ul className="mt-1 space-y-0.5">
                {missing.map((entry, index) => (
                  <li key={index} className="text-small text-mist-300">
                    <span className="mono">{entry.tool}</span> — {entry.reason}
                  </li>
                ))}
              </ul>
            </div>
          ) : null}

          {failedTools.length > 0 ? (
            <div className="rounded-lg border border-rose-primary/30 bg-rose-primary/8 px-2.5 py-2">
              <p className="text-small font-medium text-rose-300">Tool failures</p>
              <ul className="mt-1 space-y-0.5">
                {failedTools.map((call, index) => (
                  <li key={index} className="text-small text-mist-300">
                    <span className="mono">{call.tool}</span> — {call.error_message ?? call.error_code ?? "failed"}
                  </li>
                ))}
              </ul>
            </div>
          ) : null}

          {limitations.length > 0 ? (
            <ul className="space-y-0.5">
              {limitations.map((limitation, index) => (
                <li key={index} className="text-small leading-relaxed text-mist-400">
                  • {limitation}
                </li>
              ))}
            </ul>
          ) : null}

          {trace.tool_calls && trace.tool_calls.length > 0 ? (
            <details className="text-small">
              <summary className="cursor-pointer text-mist-500">Tool trace</summary>
              <ul className="mt-1 space-y-0.5">
                {trace.tool_calls.map((call, index) => (
                  <li key={index} className="mono text-small text-mist-400">
                    {call.ok ? "✓" : "✗"} {call.tool} · {call.duration_ms} ms
                    {call.arguments && Object.keys(call.arguments).length > 0
                      ? ` · ${JSON.stringify(call.arguments)}`
                      : ""}
                  </li>
                ))}
              </ul>
            </details>
          ) : null}
        </Disclosure>
      ) : null}
    </div>
  );
}
