"""Phase 11: the coaching layer that ties the earlier phases into one workflow.

Nothing in this package analyses a chess position, reads a database, or calls an
engine. It *composes* what Phases 3–10 already measured:

* :mod:`argus.coaching.context` — where the user is, and therefore how to answer.
* :mod:`argus.coaching.prioritize` — which verified finding deserves attention,
  with every factor derived from a stored measurement.
* :mod:`argus.coaching.debrief` — the automatic review of a finished game.
* :mod:`argus.coaching.feed` — today's Caissa, "what should I work on?", and a plan.

The reason this is a package rather than more code in the API layer is the same
reason the training engine is one: composition rules (what may be claimed, what
must be refused, what a priority means) are testable without a database, and the
API layer stays a thin adapter over them.
"""

from __future__ import annotations

from argus.coaching.context import (
    DEFAULT_MODE_FOR_SITUATION,
    MODE_PROFILES,
    TOOL_FAMILIES,
    CoachContext,
    CoachMode,
    ModeProfile,
    Situation,
    assemble_context,
    context_brief,
    infer_situation,
    mode_profile,
    resolve_mode,
)
from argus.coaching.collections import (
    COLLECTIONS_METHODOLOGY_VERSION,
    MAX_ITEMS_PER_COLLECTION,
    CollectionError,
    CollectionKind,
    ItemKind,
    StudyCollection,
    StudyItem,
    add_item,
    build_collection,
    collections_method,
    remove_item,
)
from argus.coaching.debrief import (
    DEBRIEF_METHODOLOGY_VERSION,
    REVIEW_STEPS,
    DebriefSection,
    GameDebrief,
    build_debrief,
)
from argus.coaching.evidence import (
    EVIDENCE_METHODOLOGY_VERSION,
    EvidenceItem,
    EvidencePacket,
    KnowledgeKind,
    build_evidence_packet,
    build_reference,
    evidence_method,
)
from argus.coaching.match_prep import (
    MATCH_PREP_METHODOLOGY_VERSION,
    SAMPLE_GATES,
    MatchPreparation,
    PrepScenario,
    PrepSection,
    PrepSectionStatus,
    build_match_preparation,
    match_brief,
    match_prep_method,
    parse_preparation_row,
)
from argus.coaching.progress import (
    CAUSALITY_NOTE,
    MIN_GAMES_PER_PERIOD,
    PROGRESS_METHODOLOGY_VERSION,
    ImprovementComparison,
    ProgressMeasure,
    ProgressSnapshot,
    build_snapshot,
    compare_periods,
    progress_method,
)
from argus.coaching.search import (
    SEARCH_METHODOLOGY_VERSION,
    SearchCandidate,
    SearchHit,
    SearchKind,
    SearchResult,
    search,
    search_method,
)
from argus.coaching.feed import (
    FEED_METHODOLOGY_VERSION,
    FEED_SECTIONS,
    PROGRESS_MEASURES,
    CoachingFeed,
    FeedAction,
    FeedCard,
    FeedSection,
    FocusAnswer,
    TrainingPlan,
    answer_focus,
    build_feed,
    build_training_plan,
    feed_method,
    mistake_candidates,
    opponent_candidates,
    profile_candidates,
)
from argus.coaching.prioritize import (
    FACTOR_WEIGHTS,
    PRIORITY_METHODOLOGY_VERSION,
    InsightCandidate,
    InsightPriority,
    ScoredInsight,
    explain_method,
    prioritize,
    priority_counts,
    score_insight,
)

__all__ = [
    "CAUSALITY_NOTE",
    "COLLECTIONS_METHODOLOGY_VERSION",
    "DEBRIEF_METHODOLOGY_VERSION",
    "DEFAULT_MODE_FOR_SITUATION",
    "EVIDENCE_METHODOLOGY_VERSION",
    "FACTOR_WEIGHTS",
    "FEED_METHODOLOGY_VERSION",
    "FEED_SECTIONS",
    "MATCH_PREP_METHODOLOGY_VERSION",
    "MAX_ITEMS_PER_COLLECTION",
    "MIN_GAMES_PER_PERIOD",
    "MODE_PROFILES",
    "PRIORITY_METHODOLOGY_VERSION",
    "PROGRESS_MEASURES",
    "PROGRESS_METHODOLOGY_VERSION",
    "REVIEW_STEPS",
    "SAMPLE_GATES",
    "SEARCH_METHODOLOGY_VERSION",
    "TOOL_FAMILIES",
    "CoachContext",
    "CoachMode",
    "CoachingFeed",
    "CollectionError",
    "CollectionKind",
    "DebriefSection",
    "EvidenceItem",
    "EvidencePacket",
    "FeedAction",
    "FeedCard",
    "FeedSection",
    "FocusAnswer",
    "GameDebrief",
    "ImprovementComparison",
    "InsightCandidate",
    "InsightPriority",
    "ItemKind",
    "KnowledgeKind",
    "MatchPreparation",
    "ModeProfile",
    "PrepScenario",
    "PrepSection",
    "PrepSectionStatus",
    "ProgressMeasure",
    "ProgressSnapshot",
    "ScoredInsight",
    "SearchCandidate",
    "SearchHit",
    "SearchKind",
    "SearchResult",
    "Situation",
    "StudyCollection",
    "StudyItem",
    "TrainingPlan",
    "add_item",
    "answer_focus",
    "assemble_context",
    "build_collection",
    "build_debrief",
    "build_evidence_packet",
    "build_feed",
    "build_match_preparation",
    "build_reference",
    "build_snapshot",
    "build_training_plan",
    "collections_method",
    "compare_periods",
    "context_brief",
    "evidence_method",
    "explain_method",
    "feed_method",
    "infer_situation",
    "match_brief",
    "match_prep_method",
    "mistake_candidates",
    "mode_profile",
    "opponent_candidates",
    "parse_preparation_row",
    "prioritize",
    "priority_counts",
    "profile_candidates",
    "progress_method",
    "remove_item",
    "resolve_mode",
    "score_insight",
    "search",
    "search_method",
]
