"""Caissa game-intelligence layer (Phase 4).

Turns the structured data produced by the engine analysis layer into structured
chess intelligence:

    engine analysis (facts)
        → board-derived features (material, structure, activity, king safety, tactics)
        → Caissa interpretation (advantage states, turning points, categories, conversion)
        → the structured, fully-evidenced GameReport

Nothing here calls Stockfish, trains a model, predicts an outcome, or writes
natural language. Every insight records its ``source``
(``engine_fact`` / ``argus_derived_feature`` / ``argus_interpretation``), its
``certainty`` (``confirmed`` / ``candidate``) and the evidence behind it, so the
future explanation layer can always answer "why?".
"""

from argus.intelligence.accuracy import (
    ACCURACY_DISCLAIMER,
    ACCURACY_METHODOLOGY,
    AccuracyAnalysis,
    MoveAccuracy,
    SideAccuracy,
    accuracy_statement,
    analyse_accuracy,
    score_move,
    win_expectation,
)
from argus.intelligence.activity import (
    PieceActivityAnalysis,
    PieceActivitySnapshot,
    SideActivity,
    activity_for,
    build_piece_activity,
)
from argus.intelligence.advantage import AdvantageState, describe_policy, state_for
from argus.intelligence.base import (
    REPORT_VERSION,
    AccuracyPolicy,
    AdvantagePolicy,
    Certainty,
    CriticalFact,
    EvidenceSource,
    Finding,
    GameContext,
    Insight,
    IntelligencePolicy,
    KingSafetyPolicy,
    MaterialPolicy,
    MoveFact,
    PositionalPolicy,
    Recommendation,
    TacticPolicy,
    TurningPointPolicy,
    Unavailable,
)
from argus.intelligence.categories import (
    CategorisedError,
    CategoryAnalysis,
    ErrorCategory,
    categorise_errors,
    category_statement,
)
from argus.intelligence.conversion import (
    ConversionAnalysis,
    ConversionEvent,
    ConversionEventType,
    analyse_conversion,
)
from argus.intelligence.forecast import (
    FORECAST_DISCLAIMER,
    FORECAST_METHODOLOGY,
    ForecastPeak,
    OutcomeProbabilities,
    ResultForecast,
    build_forecast,
    outcome_probabilities,
    win_expectation_white,
)
from argus.intelligence.king_safety import (
    KingSafetyAnalysis,
    KingSafetyEvent,
    KingSafetyEventType,
    KingSafetySide,
    build_king_safety,
    king_zone,
)
from argus.intelligence.material import (
    MaterialEvent,
    MaterialSnapshot,
    MaterialTimeline,
    build_material_timeline,
    material_points,
)
from argus.intelligence.opening_book import OPENING_LINES, book_entry_count
from argus.intelligence.openings import (
    OpeningAnalysis,
    OpeningDeviation,
    OpeningIdentification,
    detect_opening,
)
from argus.intelligence.performance import (
    PhasePerformance,
    PhaseSideStats,
    build_phase_performance,
    phase_statement,
)
from argus.intelligence.phases import GamePhaseDetector, PhaseDetection, PhaseIndicator
from argus.intelligence.positional import (
    PositionalAnalysis,
    PositionalEvent,
    PositionalEventType,
    build_positional_analysis,
    weak_squares,
)
from argus.intelligence.report import (
    EVIDENCE_POLICY,
    AccuracyReportSection,
    AnalysisProvenance,
    ConversionReportSection,
    CriticalMomentsSection,
    ErrorCategorySection,
    ForecastReportSection,
    GameReport,
    GameSummarySection,
    KingSafetyReportSection,
    MaterialReportSection,
    PhaseReportSection,
    PhaseTransition,
    PositionalReportSection,
    TacticalReportSection,
    TimelineEntry,
    TrajectoryReportSection,
    build_key_lessons,
    build_summary,
    build_training_recommendations,
)
from argus.intelligence.service import AnalysisMeta, GameIntelligence
from argus.intelligence.structure import (
    PawnStructureAnalysis,
    PawnStructureEvent,
    PawnStructureSide,
    PawnStructureSnapshot,
    build_pawn_structure,
    pawn_structure_for,
)
from argus.intelligence.tactics import (
    TacticalAnalysis,
    TacticalEvent,
    TacticType,
    detect_tactical_events,
)
from argus.intelligence.trajectory import (
    GameTrajectory,
    TrajectoryEvent,
    TrajectoryEventType,
    TrajectoryPoint,
    TrajectorySegment,
    build_trajectory,
    initial_balance_from_fen,
)
from argus.intelligence.turning_points import (
    TurningPoint,
    TurningPointAnalysis,
    TurningPointType,
    detect_turning_points,
)

__all__ = [
    "ACCURACY_DISCLAIMER",
    "ACCURACY_METHODOLOGY",
    "EVIDENCE_POLICY",
    "FORECAST_DISCLAIMER",
    "FORECAST_METHODOLOGY",
    "OPENING_LINES",
    "REPORT_VERSION",
    "AccuracyAnalysis",
    "AccuracyPolicy",
    "AccuracyReportSection",
    "AdvantagePolicy",
    "AdvantageState",
    "AnalysisMeta",
    "AnalysisProvenance",
    "CategorisedError",
    "CategoryAnalysis",
    "Certainty",
    "ConversionAnalysis",
    "ConversionEvent",
    "ConversionEventType",
    "ConversionReportSection",
    "CriticalFact",
    "CriticalMomentsSection",
    "ErrorCategory",
    "ErrorCategorySection",
    "EvidenceSource",
    "Finding",
    "ForecastPeak",
    "ForecastReportSection",
    "GameContext",
    "GameIntelligence",
    "GamePhaseDetector",
    "GameReport",
    "GameSummarySection",
    "GameTrajectory",
    "Insight",
    "IntelligencePolicy",
    "KingSafetyAnalysis",
    "KingSafetyEvent",
    "KingSafetyEventType",
    "KingSafetyPolicy",
    "KingSafetyReportSection",
    "KingSafetySide",
    "MaterialEvent",
    "MaterialPolicy",
    "MaterialReportSection",
    "MaterialSnapshot",
    "MaterialTimeline",
    "MoveAccuracy",
    "MoveFact",
    "OpeningAnalysis",
    "OpeningDeviation",
    "OpeningIdentification",
    "OutcomeProbabilities",
    "PawnStructureAnalysis",
    "PawnStructureEvent",
    "PawnStructureSide",
    "PawnStructureSnapshot",
    "PhaseDetection",
    "PhaseIndicator",
    "PhasePerformance",
    "PhaseReportSection",
    "PhaseSideStats",
    "PhaseTransition",
    "PieceActivityAnalysis",
    "PieceActivitySnapshot",
    "PositionalAnalysis",
    "PositionalEvent",
    "PositionalEventType",
    "PositionalPolicy",
    "PositionalReportSection",
    "Recommendation",
    "ResultForecast",
    "SideAccuracy",
    "SideActivity",
    "TacticPolicy",
    "TacticalAnalysis",
    "TacticalEvent",
    "TacticalReportSection",
    "TacticType",
    "TimelineEntry",
    "TrajectoryEvent",
    "TrajectoryEventType",
    "TrajectoryPoint",
    "TrajectoryReportSection",
    "TrajectorySegment",
    "TurningPoint",
    "TurningPointAnalysis",
    "TurningPointPolicy",
    "TurningPointType",
    "Unavailable",
    "accuracy_statement",
    "activity_for",
    "analyse_accuracy",
    "analyse_conversion",
    "book_entry_count",
    "build_forecast",
    "build_key_lessons",
    "build_king_safety",
    "build_material_timeline",
    "build_pawn_structure",
    "build_phase_performance",
    "build_piece_activity",
    "build_positional_analysis",
    "build_summary",
    "build_training_recommendations",
    "build_trajectory",
    "categorise_errors",
    "category_statement",
    "describe_policy",
    "detect_opening",
    "detect_tactical_events",
    "detect_turning_points",
    "initial_balance_from_fen",
    "king_zone",
    "material_points",
    "outcome_probabilities",
    "pawn_structure_for",
    "phase_statement",
    "score_move",
    "state_for",
    "weak_squares",
    "win_expectation",
    "win_expectation_white",
]
