"""The structured Game Report.

Phase 4's deliverable: one deterministic, fully evidenced document describing
what happened in a game and why Caissa says so. Every section is built from

* engine facts already stored by the Phase 3 pipeline, and
* Caissa-derived board features (structure, activity, material, king safety),

and every derived claim carries its evidence and its ``source`` level:

``engine_fact``           measured by Stockfish
``argus_derived_feature`` measured from the board by Caissa code
``argus_interpretation``  a rule Caissa applies (loops, candidates, categories)

There is **no prose generation** and no LLM anywhere in this module. Statements
are factual templates filled with measurements, e.g. "White's largest evaluation
drop occurred after move 28 (-420cp)." — a fact, not a judgement. The final two
sections (key lessons, training recommendations) are structured,
evidence-carrying lists rather than narrative text.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from argus.analysis.phase import GamePhase
from argus.chess_core.models import Color
from argus.intelligence.accuracy import AccuracyAnalysis, SideAccuracy, accuracy_statement
from argus.intelligence.base import (
    REPORT_VERSION,
    Certainty,
    EvidenceSource,
    Finding,
    GameContext,
    Insight,
    MoveFact,
    Recommendation,
    Unavailable,
    color_label,
)
from argus.intelligence.categories import CategoryAnalysis, category_statement
from argus.intelligence.conversion import ConversionAnalysis, ConversionEventType
from argus.intelligence.forecast import ResultForecast
from argus.intelligence.king_safety import KingSafetyAnalysis, KingSafetyEventType
from argus.intelligence.material import MaterialTimeline
from argus.intelligence.openings import OpeningAnalysis
from argus.intelligence.performance import PhasePerformance, phase_statement
from argus.intelligence.positional import PositionalAnalysis
from argus.intelligence.tactics import TacticalAnalysis
from argus.intelligence.trajectory import GameTrajectory
from argus.intelligence.turning_points import TurningPointAnalysis, TurningPointType

EVIDENCE_POLICY = (
    "Every insight records its source (engine_fact / argus_derived_feature / "
    "argus_interpretation), its certainty (confirmed / candidate) and the raw evidence it "
    "was derived from. No statistic in this report is estimated, sampled, predicted or "
    "generated by a language model."
)


class PhaseTransition(BaseModel):
    """A ply where the detected game phase changed."""

    ply: int
    move_number: int
    from_phase: GamePhase
    to_phase: GamePhase
    reasons: list[str] = Field(default_factory=list)
    statement: str


class PhaseReportSection(BaseModel):
    """Game-phase detection plus phase-specific performance."""

    final_phase: GamePhase
    phase_by_ply: dict[str, str] = Field(
        default_factory=dict, description="Per-ply phase labels (string keys for JSON)"
    )
    transitions: list[PhaseTransition] = Field(default_factory=list)
    phase_indicators_final: list[str] = Field(default_factory=list)
    detector_confidence_final: float | None = None
    performance: PhasePerformance
    facts: list[Finding] = Field(default_factory=list)


class TimelineEntry(BaseModel):
    """One entry of the critical-moment timeline (clickable in the UI)."""

    ply: int
    move_number: int | None = None
    san: str | None = None
    side: Color | None = None
    kind: str
    label: str
    statement: str
    severity: str = "low"
    source: EvidenceSource = EvidenceSource.ARGUS_DERIVED_FEATURE
    certainty: Certainty = Certainty.CONFIRMED
    evidence: dict[str, Any] = Field(default_factory=dict)


class CriticalMomentsSection(BaseModel):
    """Critical positions from Phase 3 plus the merged intelligence timeline."""

    engine_critical_moments: list[Insight] = Field(default_factory=list)
    timeline: list[TimelineEntry] = Field(default_factory=list)
    largest_swing_ply: int | None = None
    note: str = (
        "Large swings are candidates, not verdicts. The timeline merges engine-flagged "
        "critical positions with Caissa-detected turning points, tactics and conversion events."
    )


class MaterialReportSection(BaseModel):
    """Material history and its events."""

    timeline: MaterialTimeline
    facts: list[Finding] = Field(default_factory=list)


class TacticalReportSection(BaseModel):
    """Tactical events (confirmed facts and candidates, clearly separated)."""

    analysis: TacticalAnalysis
    facts: list[Finding] = Field(default_factory=list)


class PositionalReportSection(BaseModel):
    """Positional features and error candidates."""

    analysis: PositionalAnalysis
    facts: list[Finding] = Field(default_factory=list)


class KingSafetyReportSection(BaseModel):
    """King-safety measurements and events."""

    analysis: KingSafetyAnalysis
    facts: list[Finding] = Field(default_factory=list)


class TrajectoryReportSection(BaseModel):
    """Evaluation trajectory, advantage bands and advantage states."""

    trajectory: GameTrajectory
    advantage_thresholds: dict[str, Any] = Field(default_factory=dict)
    states_seen: list[str] = Field(default_factory=list)
    facts: list[Finding] = Field(default_factory=list)


class AccuracyReportSection(BaseModel):
    """Caissa accuracy (methodology included) plus raw centipawn loss."""

    analysis: AccuracyAnalysis
    facts: list[Finding] = Field(default_factory=list)


class ConversionReportSection(BaseModel):
    """Conversion / comeback observations."""

    analysis: ConversionAnalysis
    facts: list[Finding] = Field(default_factory=list)


class ErrorCategorySection(BaseModel):
    """Evidence-derived error categories."""

    analysis: CategoryAnalysis
    facts: list[Finding] = Field(default_factory=list)


class AnalysisProvenance(BaseModel):
    """Where the underlying engine data came from (audit trail)."""

    analysis_version: str | None = None
    report_version: str = REPORT_VERSION
    engine: str | None = None
    engine_version: str | None = None
    depth: int | None = None
    multipv: int | None = None
    movetime_ms: int | None = None
    profile: str | None = None
    positions_analyzed: int = 0
    moves_in_game: int = 0
    evaluated_moves: int = 0
    engine_calls_made_by_intelligence_layer: int = Field(
        default=0,
        description="The intelligence layer never runs Stockfish; this is always 0",
    )


class GameSummarySection(BaseModel):
    """Top-level facts about the game."""

    white_player: str
    black_player: str
    white_rating: int | None = None
    black_rating: int | None = None
    result: str
    result_label: str
    date: str | None = None
    event: str | None = None
    time_control: str | None = None
    moves: int
    opening_name: str | None = None
    eco_code: str | None = None
    phase_with_largest_drop: dict[str, str | None] = Field(default_factory=dict)
    facts: list[Finding] = Field(default_factory=list)


class ForecastReportSection(BaseModel):
    """Engine-derived outcome forecast, with its methodology attached.

    Caissa interpretation over an engine fact — never a trained model, and never
    presented without the curve that produced it.
    """

    forecast: ResultForecast
    facts: list[Finding] = Field(default_factory=list)


class GameReport(BaseModel):
    """The complete structured Caissa game report."""

    report_version: str = REPORT_VERSION
    generated_at: datetime
    game_id: str | None = None
    context: GameContext
    provenance: AnalysisProvenance
    summary: GameSummarySection
    opening: OpeningAnalysis
    phases: PhaseReportSection
    trajectory: TrajectoryReportSection
    material: MaterialReportSection
    tactical: TacticalReportSection
    positional: PositionalReportSection
    king_safety: KingSafetyReportSection
    accuracy: AccuracyReportSection
    forecast: ForecastReportSection | None = None
    conversion: ConversionReportSection
    error_categories: ErrorCategorySection
    turning_points: TurningPointAnalysis
    critical_moments: CriticalMomentsSection
    key_lessons: list[Finding] = Field(default_factory=list)
    training_recommendations: list[Recommendation] = Field(default_factory=list)
    unavailable: list[Unavailable] = Field(default_factory=list)
    evidence_policy: str = EVIDENCE_POLICY

    @property
    def outcome(self) -> str:
        return _result_label(self.context.result)


def _result_label(result: str) -> str:
    return {
        "1-0": "White won",
        "0-1": "Black won",
        "1/2-1/2": "Draw",
    }.get(result, "Result unknown")


# --- the summary engine --------------------------------------------------------


def build_summary(
    context: GameContext,
    moves: list[MoveFact],
    *,
    opening: OpeningAnalysis,
    performance: PhasePerformance,
    accuracy: AccuracyAnalysis,
    material: MaterialTimeline,
    tactical: TacticalAnalysis,
    turning_points: TurningPointAnalysis,
    conversion: ConversionAnalysis,
) -> GameSummarySection:
    """Deterministic, factual summary statements (no commentary)."""
    facts: list[Finding] = []
    result_label = _result_label(context.result)
    facts.append(
        Finding(
            key="result",
            statement=(
                f"{context.white_player} played {context.black_player}; the game ended {result_label}."
            ),
            evidence={"result": context.result, "moves": len(moves)},
        )
    )

    if opening.identification.source != "unclassified":
        facts.append(
            Finding(
                key="opening",
                statement=(
                    f"The game opened as {opening.identification.name} "
                    f"({opening.identification.eco}), identified from "
                    f"{opening.identification.source}."
                ),
                evidence={
                    "eco": opening.identification.eco,
                    "matched_plies": opening.identification.matched_plies,
                },
            )
        )
    else:
        facts.append(
            Finding(
                key="opening",
                statement=(
                    "The opening could not be identified from the move sequence; it is "
                    "reported as unknown rather than guessed."
                ),
                evidence={"table_lines": opening.book_lines},
            )
        )

    if opening.deviation.deviated and opening.deviation.ply is not None:
        facts.append(
            Finding(
                key="opening_deviation",
                statement=(
                    f"The game left the known line on move {opening.deviation.move_number} "
                    f"with {opening.deviation.played_san}; leaving a line is not by itself a mistake."
                ),
                ply=opening.deviation.ply,
                move_number=opening.deviation.move_number,
                side=opening.deviation.side,
                evidence={
                    "expected_continuation": opening.deviation.expected_continuation_san,
                    "played": opening.deviation.played_san,
                },
            )
        )

    # Largest evaluation drop per side (engine fact).
    for color in (Color.WHITE, Color.BLACK):
        losses = [
            (fact.centipawn_loss or 0, fact)
            for fact in moves
            if fact.mover == color and fact.centipawn_loss is not None
        ]
        if not losses:
            continue
        loss, worst = max(losses, key=lambda item: item[0])
        facts.append(
            Finding(
                key=f"largest_drop_{color.value}",
                statement=(
                    f"{color_label(color)}'s largest evaluation drop occurred after move "
                    f"{worst.move_number} ({worst.san}), losing {loss}cp."
                ),
                ply=worst.ply,
                move_number=worst.move_number,
                side=color,
                evidence={
                    "centipawn_loss": loss,
                    "classification": worst.classification.value
                    if worst.classification
                    else None,
                    "best_move_san": worst.best_move_san,
                    "evaluation_before_white": worst.eval_before_white,
                    "evaluation_after_white": worst.eval_after_white,
                },
            )
        )

    # Flagged-move counts per side (engine facts).
    for color in (Color.WHITE, Color.BLACK):
        own = [fact for fact in moves if fact.mover == color and fact.classification is not None]
        counts: dict[str, int] = {}
        for fact in own:
            classification = fact.classification
            if classification is not None:
                counts[classification.value] = counts.get(classification.value, 0) + 1
        mistakes = counts.get("mistake", 0)
        blunders = counts.get("blunder", 0)
        facts.append(
            Finding(
                key=f"flagged_moves_{color.value}",
                statement=(
                    f"The engine classified {mistakes} mistake(s) and {blunders} blunder(s) "
                    f"for {color_label(color)}, out of {len(own)} classified moves."
                ),
                side=color,
                evidence={"counts": counts, "classified_moves": len(own)},
            )
        )

    for color in (Color.WHITE, Color.BLACK):
        phase_key = (
            performance.worst_phase_white if color == Color.WHITE else performance.worst_phase_black
        )
        if phase_key:
            facts.append(
                Finding(
                    key=f"worst_phase_{color.value}",
                    statement=phase_statement(performance, color),
                    side=color,
                    evidence={"phase": phase_key},
                )
            )

    for side in (accuracy.white, accuracy.black):
        facts.append(
            Finding(
                key=f"accuracy_{side.side.value}",
                statement=accuracy_statement(side),
                side=side.side,
                evidence={
                    "accuracy": side.accuracy,
                    "scored_moves": side.scored_moves,
                    "excluded": side.excluded_decided_moves,
                    "average_centipawn_loss": side.average_centipawn_loss,
                },
            )
        )

    if material.transitions:
        current = material.transitions[0]
        total = len(material.transitions)
        facts.append(
            Finding(
                key="material_transitions",
                statement=(
                    f"The material balance changed by at least 2 pawns on {total} move(s); the "
                    f"first was move {current.move_number} ({current.san}), balance "
                    f"{current.balance_before} to {current.balance_after} pawns."
                ),
                ply=current.ply,
                move_number=current.move_number,
                side=current.side,
                evidence={
                    "total_transitions": total,
                    "total_captures": material.total_captures,
                    "exchanges": material.exchanges,
                    "final_balance": material.final_balance,
                },
            )
        )
    if material.promotions:
        promotion = material.promotions[0]
        facts.append(
            Finding(
                key="promotions",
                statement=(
                    f"{color_label(promotion.side)} promoted on move {promotion.move_number} "
                    f"({promotion.san}) to a {promotion.promoted_to}."
                ),
                ply=promotion.ply,
                move_number=promotion.move_number,
                side=promotion.side,
                evidence={"promotion_count": len(material.promotions)},
            )
        )

    if tactical.events:
        confirmed = tactical.confirmed_count
        candidates = tactical.candidate_count
        facts.append(
            Finding(
                key="tactical_events",
                statement=(
                    f"Caissa detected {confirmed} confirmed tactical event(s) and {candidates} "
                    f"candidate event(s) across the game."
                ),
                evidence={"by_type": tactical.by_type, "by_side": tactical.by_side},
            )
        )
    else:
        facts.append(
            Finding(
                key="tactical_events",
                statement="Caissa detected no tactical events from the board states of this game.",
                evidence={},
            )
        )

    if turning_points.turning_points:
        biggest = max(turning_points.turning_points, key=lambda point: point.severity_score)
        facts.append(
            Finding(
                key="turning_points",
                statement=(
                    f"Caissa identified {len(turning_points.turning_points)} turning point(s); the "
                    f"most severe was move {biggest.move_number} ({biggest.san}), {biggest.type.value}."
                ),
                ply=biggest.ply,
                move_number=biggest.move_number,
                side=biggest.side,
                evidence={"by_type": turning_points.by_type, "largest_swing_ply": turning_points.largest_swing_ply},
            )
        )

    for event in conversion.events:
        if event.type is ConversionEventType.ADVANTAGE_CONVERSION_CANDIDATE:
            facts.append(
                Finding(
                    key=f"conversion_candidate_{event.side.value}",
                    statement=event.statement,
                    ply=event.ply,
                    move_number=event.move_number,
                    side=event.side,
                    source=EvidenceSource.ARGUS_INTERPRETATION,
                    evidence=event.evidence,
                )
            )

    opening_name = opening.identification.name or context.opening_name
    eco_code = opening.identification.eco or context.eco_code
    return GameSummarySection(
        white_player=context.white_player,
        black_player=context.black_player,
        white_rating=context.white_rating,
        black_rating=context.black_rating,
        result=context.result,
        result_label=result_label,
        date=context.date,
        event=context.event,
        time_control=context.time_control,
        moves=len(moves),
        opening_name=opening_name,
        eco_code=eco_code,
        phase_with_largest_drop={
            "white": performance.worst_phase_white,
            "black": performance.worst_phase_black,
        },
        facts=facts,
    )


# --- key lessons & training recommendations -----------------------------------


def build_key_lessons(
    *,
    summary: GameSummarySection,
    opening: OpeningAnalysis,
    performance: PhasePerformance,
    accuracy: AccuracyAnalysis,
    tactical: TacticalAnalysis,
    positional: PositionalAnalysis,
    king_safety: KingSafetyAnalysis,
    categories: CategoryAnalysis,
    turning_points: TurningPointAnalysis,
    conversion: ConversionAnalysis,
) -> list[Finding]:
    """Evidence-based findings — each one a fact with the data behind it."""
    lessons: list[Finding] = []

    for side in (accuracy.white, accuracy.black):
        if side.accuracy is None:
            continue
        decided = side.excluded_decided_moves
        lessons.append(
            Finding(
                key=f"accuracy_{side.side.value}",
                statement=(
                    f"{color_label(side.side)} scored {side.accuracy:.2f} Caissa accuracy over "
                    f"{side.scored_moves} scored moves"
                    + (f" ({decided} already-decided moves excluded)." if decided else ".")
                ),
                side=side.side,
                evidence={
                    "accuracy": side.accuracy,
                    "average_centipawn_loss": side.average_centipawn_loss,
                    "scored_moves": side.scored_moves,
                    "small_sample": side.small_sample,
                },
            )
        )

    # Where each side's accuracy was actually spent. A statement is only made
    # when the weakest slice holds enough scored moves to mean something, and
    # the exact/approximate split of the comparison is always reported.
    for breakdown in (accuracy.breakdown.white, accuracy.breakdown.black):
        if breakdown.by_phase:
            weakest = min(
                (group for group in breakdown.by_phase if group.accuracy is not None),
                key=lambda group: group.accuracy or 0.0,
                default=None,
            )
            if weakest is not None and not weakest.small_sample:
                lessons.append(
                    Finding(
                        key=f"accuracy_weakest_phase_{breakdown.side.value}",
                        statement=(
                            f"{color_label(breakdown.side)}'s lowest accuracy came in the "
                            f"{weakest.label} ({weakest.accuracy:.2f} over "
                            f"{weakest.scored_moves} scored move(s))."
                        ),
                        side=breakdown.side,
                        source=EvidenceSource.ARGUS_DERIVED_FEATURE,
                        evidence={
                            "phase": weakest.key,
                            "accuracy": weakest.accuracy,
                            "scored_moves": weakest.scored_moves,
                            "share_of_loss": weakest.share_of_loss,
                        },
                    )
                )
        if breakdown.by_material_state:
            weakest = min(
                (group for group in breakdown.by_material_state if group.accuracy is not None),
                key=lambda group: group.accuracy or 0.0,
                default=None,
            )
            if weakest is not None and not weakest.small_sample:
                lessons.append(
                    Finding(
                        key=f"accuracy_material_state_{breakdown.side.value}",
                        statement=(
                            f"{color_label(breakdown.side)}'s accuracy was lowest while "
                            f"{weakest.label.lower()} ({weakest.accuracy:.2f} over "
                            f"{weakest.scored_moves} scored move(s))."
                        ),
                        side=breakdown.side,
                        source=EvidenceSource.ARGUS_DERIVED_FEATURE,
                        evidence={
                            "material_state": weakest.key,
                            "accuracy": weakest.accuracy,
                            "scored_moves": weakest.scored_moves,
                        },
                    )
                )
        side_accuracy = accuracy.white if breakdown.side == Color.WHITE else accuracy.black
        if side_accuracy.approximate_scores:
            lessons.append(
                Finding(
                    key=f"accuracy_approximation_{breakdown.side.value}",
                    statement=(
                        f"{side_accuracy.approximate_scores} of "
                        f"{color_label(breakdown.side)}'s scored moves had no score inside the "
                        "best-line search, so they were measured from a separate search of the "
                        "resulting position (approximate)."
                    ),
                    side=breakdown.side,
                    source=EvidenceSource.ARGUS_DERIVED_FEATURE,
                    evidence={
                        "exact_scores": side_accuracy.exact_scores,
                        "approximate_scores": side_accuracy.approximate_scores,
                    },
                )
            )

    for color in (Color.WHITE, Color.BLACK):
        bucket = categories.by_side_category.get(color.value, {})
        if bucket:
            top = max(bucket.items(), key=lambda item: item[1])
            lessons.append(
                Finding(
                    key=f"top_category_{color.value}",
                    statement=(
                        f"{category_statement(categories, color)} The most frequent category is "
                        f"{top[0]} ({top[1]} move(s))."
                    ),
                    side=color,
                    source=EvidenceSource.ARGUS_INTERPRETATION,
                    evidence={"by_category": bucket},
                )
            )

    if turning_points.turning_points:
        for point in turning_points.turning_points:
            if point.type not in {
                TurningPointType.MISSED_WIN,
                TurningPointType.MATE_CHANGE,
                TurningPointType.CONVERSION_FAILURE,
                TurningPointType.ADVANTAGE_LOST,
            }:
                continue
            lessons.append(
                Finding(
                    key=f"turning_point_{point.type.value}_{point.ply}",
                    statement=point.statement,
                    ply=point.ply,
                    move_number=point.move_number,
                    side=point.side,
                    source=EvidenceSource.ARGUS_INTERPRETATION,
                    evidence={
                        "type": point.type.value,
                        "severity": point.severity,
                        "evaluation_before_cp": point.evaluation_before_cp,
                        "evaluation_after_cp": point.evaluation_after_cp,
                        "certainty": point.certainty.value,
                    },
                )
            )

    for event in conversion.events:
        if event.type is ConversionEventType.CONVERSION_CONFIRMED:
            continue
        lessons.append(
            Finding(
                key=f"conversion_{event.type.value}_{event.ply}",
                statement=event.statement,
                ply=event.ply,
                move_number=event.move_number,
                side=event.side,
                source=EvidenceSource.ARGUS_INTERPRETATION,
                evidence=event.evidence,
            )
        )

    if tactical.by_type:
        for side in (Color.WHITE, Color.BLACK):
            against = [
                event
                for event in tactical.events
                if event.side != side and event.certainty == Certainty.CONFIRMED
            ]
            if not against:
                continue
            counts: dict[str, int] = {}
            for event in against:
                counts[event.type.value] = counts.get(event.type.value, 0) + 1
            top = max(counts.items(), key=lambda item: item[1])
            lessons.append(
                Finding(
                    key=f"tactics_against_{side.value}",
                    statement=(
                        f"{len(against)} confirmed tactical event(s) by the opponent affected "
                        f"{color_label(side)}; the most common type was {top[0]} ({top[1]})."
                    ),
                    side=side,
                    source=EvidenceSource.ARGUS_INTERPRETATION,
                    evidence={
                        "counts": counts,
                        "plies": [event.ply for event in against][:12],
                    },
                )
            )

    for side in (Color.WHITE, Color.BLACK):
        worst = king_safety.worst_white if side == Color.WHITE else king_safety.worst_black
        if worst is None:
            continue
        own = worst.white if side == Color.WHITE else worst.black
        lessons.append(
            Finding(
                key=f"worst_king_safety_{side.value}",
                statement=(
                    f"{color_label(side)}'s most exposed king position was at ply {worst.ply}: "
                    f"{own.pawn_shield} shield pawn(s), {own.enemy_attackers_near_king} attacker(s) "
                    f"on the king zone, exposure score {own.score}."
                ),
                ply=worst.ply,
                move_number=worst.move_number,
                side=side,
                evidence={
                    "king_square": own.king_square,
                    "open_files_near_king": own.open_files_near_king,
                    "king_mobility": own.king_mobility,
                    "severity": own.severity,
                },
            )
        )

    final_weak = {
        Color.WHITE: positional.weak_squares_white,
        Color.BLACK: positional.weak_squares_black,
    }
    for color, squares in final_weak.items():
        if not squares:
            continue
        lessons.append(
            Finding(
                key=f"weak_squares_{color.value}",
                statement=(
                    f"In the final position {color_label(color)} has {len(squares)} square(s) "
                    f"that no pawn can defend and that an enemy pawn attacks: "
                    f"{', '.join(squares[:8])}."
                ),
                side=color,
                evidence={"squares": squares, "final_position": True},
            )
        )

    if positional.error_candidate_count:
        lessons.append(
            Finding(
                key="positional_error_candidates",
                statement=(
                    f"Caissa flagged {positional.error_candidate_count} positional error "
                    f"candidate(s), i.e. structural changes on moves the engine measured as "
                    f"costing at least 100cp."
                ),
                source=EvidenceSource.ARGUS_INTERPRETATION,
                evidence={"by_type": positional.by_type},
            )
        )

    if opening.deviation.deviated:
        lessons.append(
            Finding(
                key="opening_deviation_lesson",
                statement=(
                    f"The game left the Caissa opening table on move "
                    f"{opening.deviation.move_number}; the table expected "
                    f"{', '.join(opening.deviation.expected_continuation_san) or 'no further book moves'}. "
                    "Deviation is recorded as a fact, not as an error."
                ),
                ply=opening.deviation.ply,
                move_number=opening.deviation.move_number,
                side=opening.deviation.side,
                evidence={"expected_continuation_uci": opening.deviation.expected_continuation_uci},
            )
        )

    for color in (Color.WHITE, Color.BLACK):
        phase_key = (
            performance.worst_phase_white if color == Color.WHITE else performance.worst_phase_black
        )
        stats = (
            performance.white.get(phase_key) if color == Color.WHITE else performance.black.get(phase_key)
        )
        if phase_key is None or stats is None:
            continue
        lessons.append(
            Finding(
                key=f"phase_deterioration_{color.value}",
                statement=(
                    f"{color_label(color)}'s largest mean centipawn loss was in the {phase_key}: "
                    f"{stats.average_centipawn_loss}cp over {stats.moves} moves"
                    + (" (small sample)." if stats.small_sample else ".")
                ),
                side=color,
                evidence={
                    "phase": phase_key,
                    "moves": stats.moves,
                    "problem_moves": stats.problem_moves,
                    "tactical_events": stats.tactical_events,
                    "small_sample": stats.small_sample,
                },
            )
        )
    lessons.append(
        Finding(
            key="phase_methodology",
            statement=(
                "Phase comparison uses the Caissa board-state phase detector; sample sizes are "
                "reported with every phase statistic."
            ),
            evidence={"phases_present": list(performance.phase_move_counts)},
        )
    )

    lessons.append(
        Finding(
            key="largest_swing_note",
            statement=(
                "The single largest centipawn change in the game happened at ply "
                f"{turning_points.largest_swing_ply}."
                if turning_points.largest_swing_ply is not None
                else "The game contains no evaluated moves, so no swing can be reported."
            ),
            ply=turning_points.largest_swing_ply,
            evidence={"candidates_considered": turning_points.candidates_considered},
        )
    )
    return lessons


def build_training_recommendations(
    *,
    tactical: TacticalAnalysis,
    categories: CategoryAnalysis,
    performance: PhasePerformance,
    conversion: ConversionAnalysis,
    king_safety: KingSafetyAnalysis,
    positional: PositionalAnalysis,
    accuracy: AccuracyAnalysis,
) -> list[Recommendation]:
    """Rule-derived training focuses, each traced to the plies that produced it.

    These are Caissa *rules applied to detected evidence* — no model, no
    prediction, and no claims about rating or future performance.
    """
    recommendations: list[Recommendation] = []

    for side in (Color.WHITE, Color.BLACK):
        # 1. Recurring tactical pattern against this side.
        against: dict[str, list[int]] = {}
        for event in tactical.events:
            if event.side == side or event.certainty != Certainty.CONFIRMED:
                continue
            against.setdefault(event.type.value, []).append(event.ply)
        top = sorted(against.items(), key=lambda item: len(item[1]), reverse=True)
        if top and len(top[0][1]) >= 2:
            name, plies = top[0]
            recommendations.append(
                Recommendation(
                    key=f"tactics_{name}_{side.value}",
                    focus=f"Tactical pattern: opponent {name.replace('_', ' ')}",
                    rationale=(
                        f"Caissa verified {len(plies)} confirmed {name.replace('_', ' ')} "
                        f"event(s) created against {color_label(side)}; repeated patterns are "
                        f"worth reviewing on the board."
                    ),
                    evidence_refs=plies[:10],
                    observed_count=len(plies),
                )
            )

        # 2. Category with the most flagged moves.
        bucket = categories.by_side_category.get(side.value, {})
        if bucket:
            category, count = max(bucket.items(), key=lambda item: item[1])
            if count >= 2 and category != "unclassified":
                focus = {
                    "tactical": "Tactical calculation and forcing moves",
                    "material": "Material safety and piece protection",
                    "king_safety": "King safety before opening lines",
                    "opening": "Opening move orders",
                    "endgame": "Endgame technique",
                    "positional": "Positional structure and piece placement",
                }[category]
                plies = [
                    error.ply
                    for error in categories.errors
                    if error.side == side and error.category.value == category
                ]
                recommendations.append(
                    Recommendation(
                        key=f"category_{category}_{side.value}",
                        focus=focus,
                        rationale=(
                            f"{count} of {color_label(side)}'s engine-flagged moves were "
                            f"categorised as {category} from detected evidence."
                        ),
                        evidence_refs=plies[:10],
                        observed_count=count,
                    )
                )

        # 3. Phase with the largest measured deterioration.
        phase_key = (
            performance.worst_phase_white if side == Color.WHITE else performance.worst_phase_black
        )
        stats = (
            performance.white.get(phase_key) if side == Color.WHITE else performance.black.get(phase_key)
        )
        if phase_key and stats and stats.problem_moves >= 2 and not stats.small_sample:
            recommendations.append(
                Recommendation(
                    key=f"phase_{phase_key}_{side.value}",
                    focus=f"{phase_key.capitalize()} play",
                    rationale=(
                        f"{color_label(side)}'s mean centipawn loss in the {phase_key} was "
                        f"{stats.average_centipawn_loss}cp over {stats.moves} moves, with "
                        f"{stats.problem_moves} flagged move(s)."
                    ),
                    evidence_refs=stats.plies[:10],
                    observed_count=stats.problem_moves,
                )
            )

        # 4. Conversion candidates.
        candidates = [
            event
            for event in conversion.events
            if event.side == side
            and event.type is ConversionEventType.ADVANTAGE_CONVERSION_CANDIDATE
        ]
        if candidates:
            recommendations.append(
                Recommendation(
                    key=f"conversion_{side.value}",
                    focus="Converting an advantage",
                    rationale=(
                        f"Caissa measured {len(candidates)} sequence(s) where {color_label(side)} "
                        f"held a winning evaluation that later dropped to at most a slight advantage."
                    ),
                    evidence_refs=[event.ply for event in candidates][:10],
                    observed_count=len(candidates),
                )
            )

        # 5. King safety.
        exposed = [
            event
            for event in king_safety.events
            if event.side == side
            and event.severity in {"medium", "high"}
            and event.type
            in {
                KingSafetyEventType.PAWN_SHIELD_REDUCED,
                KingSafetyEventType.OPEN_FILE_NEAR_KING,
                KingSafetyEventType.KING_EXPOSED,
                KingSafetyEventType.MATING_NET,
            }
        ]
        if len(exposed) >= 2:
            recommendations.append(
                Recommendation(
                    key=f"king_safety_{side.value}",
                    focus="King safety",
                    rationale=(
                        f"{len(exposed)} king-safety event(s) of medium or high severity were "
                        f"measured for {color_label(side)}."
                    ),
                    evidence_refs=[event.ply for event in exposed][:10],
                    observed_count=len(exposed),
                )
            )

        # 6. Accuracy caveat as a data-quality note (never a rating claim).
        side_accuracy: SideAccuracy = accuracy.white if side == Color.WHITE else accuracy.black
        if side_accuracy.unscored_moves:
            recommendations.append(
                Recommendation(
                    key=f"coverage_{side.value}",
                    focus="Analysis coverage",
                    rationale=(
                        f"{side_accuracy.unscored_moves} of {color_label(side)}'s moves have no "
                        f"engine evaluation, so their conclusions are based on the evaluated subset."
                    ),
                    evidence_refs=[],
                    observed_count=side_accuracy.unscored_moves,
                )
            )

        if positional.error_candidate_count:
            plies = [event.ply for event in positional.events if event.classification == "error_candidate"]
            if len(plies) >= 2:
                recommendations.append(
                    Recommendation(
                        key=f"structure_{side.value}",
                        focus="Pawn structure decisions",
                        rationale=(
                            "Caissa flagged structural changes (isolated, doubled, backward or "
                            "lost pawn control) on moves the engine measured as costly."
                        ),
                        evidence_refs=plies[:10],
                        observed_count=len(plies),
                    )
                )

    # Deduplicate by key, keeping the highest observed count.
    deduped: dict[str, Recommendation] = {}
    for recommendation in recommendations:
        existing = deduped.get(recommendation.key)
        if existing is None or recommendation.observed_count > existing.observed_count:
            deduped[recommendation.key] = recommendation
    return sorted(deduped.values(), key=lambda item: item.observed_count, reverse=True)
